<?php
/**
 * Plugin Name: SEO Tool Bridge
 * Plugin URI: https://github.com/IamRamgarhia/SEO-Tool
 * Description: Connects this WordPress site to the self-hosted SEO Tool by DiceCodes. Lets the tool read + write meta titles, descriptions, alt text, schema, and create posts — with full revision history and one-click undo. Compatible with Yoast / Rank Math / All in One SEO.
 * Version: 0.2.0
 * Requires at least: 6.0
 * Tested up to: 6.7
 * Requires PHP: 8.0
 * Author: DiceCodes
 * Author URI: https://dicecodes.com
 * License: PolyForm Noncommercial 1.0.0
 * License URI: https://polyformproject.org/licenses/noncommercial/1.0.0/
 * Text Domain: seo-tool-bridge
 *
 * Architecture: a single connection key (generated by this plugin, pasted into
 * SEO Tool settings) authenticates inbound REST requests. Every write is
 * logged + the previous value is saved as a revision so the SEO Tool can
 * offer one-click undo per CLAUDE.md §3.5.
 */

if (!defined('ABSPATH')) {
    exit;
}

define('STB_VERSION', '0.2.0');
define('STB_OPTION_KEY', 'stb_connection_key');
define('STB_OPTION_REVISIONS', 'stb_revisions');
define('STB_REST_NAMESPACE', 'seo-tool/v1');

// =====================
// Setup + key generation
// =====================

register_activation_hook(__FILE__, function () {
    if (!get_option(STB_OPTION_KEY)) {
        update_option(STB_OPTION_KEY, wp_generate_password(48, false, false));
    }
    if (get_option(STB_OPTION_REVISIONS) === false) {
        update_option(STB_OPTION_REVISIONS, []);
    }
});

// =====================
// Settings page (Tools menu)
// =====================

add_action('admin_menu', function () {
    add_management_page(
        __('SEO Tool Bridge', 'seo-tool-bridge'),
        __('SEO Tool Bridge', 'seo-tool-bridge'),
        'manage_options',
        'seo-tool-bridge',
        'stb_render_admin_page'
    );
});

function stb_render_admin_page(): void
{
    if (!current_user_can('manage_options')) {
        return;
    }

    if (
        isset($_POST['stb_regenerate']) &&
        check_admin_referer('stb_regenerate_action', 'stb_nonce')
    ) {
        update_option(STB_OPTION_KEY, wp_generate_password(48, false, false));
        echo '<div class="updated notice"><p>New connection key generated. Update it in the SEO Tool settings.</p></div>';
    }

    $key = get_option(STB_OPTION_KEY);
    $rest_url = rest_url(STB_REST_NAMESPACE);
    ?>
    <div class="wrap">
        <h1>SEO Tool Bridge</h1>
        <p>Connects this WordPress site to your self-hosted SEO Tool, so AI suggestions can be applied with one click instead of copy-paste.</p>

        <h2>Connection details</h2>
        <table class="form-table">
            <tr>
                <th scope="row"><label>REST endpoint</label></th>
                <td>
                    <input type="text" readonly value="<?php echo esc_attr($rest_url); ?>" class="regular-text" onclick="this.select()" />
                    <p class="description">Paste this into SEO Tool → Settings → CMS connections.</p>
                </td>
            </tr>
            <tr>
                <th scope="row"><label>Connection key</label></th>
                <td>
                    <input type="text" readonly value="<?php echo esc_attr($key); ?>" class="regular-text" onclick="this.select()" />
                    <p class="description">Treat this like a password. Anyone with the key can edit your site's SEO settings.</p>
                </td>
            </tr>
        </table>

        <form method="post">
            <?php wp_nonce_field('stb_regenerate_action', 'stb_nonce'); ?>
            <p>
                <button type="submit" name="stb_regenerate" class="button button-secondary"
                        onclick="return confirm('Regenerate the key? The old key will stop working immediately.');">
                    Regenerate key
                </button>
            </p>
        </form>

        <h2>What this plugin can do</h2>
        <ul style="list-style: disc; margin-left: 20px;">
            <li>Read + write the post / page / product title</li>
            <li>Read + write the meta description (Yoast / Rank Math / All in One SEO compatible — writes to all three so it sticks regardless of which is active)</li>
            <li>Read + write image alt text in the Media Library</li>
            <li>Inject JSON-LD schema markup into &lt;head&gt; on singular pages</li>
            <li>List + look up posts by URL (used by the SEO Tool's one-click fix flow)</li>
            <li>Create new posts (draft or published) — used by the daily AI agent</li>
            <li>Full revision log with one-click undo on every change</li>
        </ul>
        <p style="color: #666; font-size: 12px;">
            Redirects + robots.txt management are <em>coming in 0.3.0</em>.
        </p>

        <h2>Recent changes</h2>
        <?php stb_render_revisions(); ?>
    </div>
    <?php
}

function stb_render_revisions(): void
{
    $revisions = get_option(STB_OPTION_REVISIONS, []);
    if (empty($revisions)) {
        echo '<p>No changes applied yet.</p>';
        return;
    }
    echo '<table class="widefat striped" style="max-width: 900px;">';
    echo '<thead><tr><th>When</th><th>Field</th><th>Object</th><th>Old → New</th></tr></thead><tbody>';
    foreach (array_slice(array_reverse($revisions), 0, 30) as $r) {
        printf(
            '<tr><td>%s</td><td>%s</td><td>%s</td><td><code>%s</code> → <code>%s</code></td></tr>',
            esc_html(date('Y-m-d H:i', $r['ts'])),
            esc_html($r['field']),
            esc_html($r['object']),
            esc_html(mb_substr((string)($r['old'] ?? ''), 0, 80)),
            esc_html(mb_substr((string)($r['new'] ?? ''), 0, 80))
        );
    }
    echo '</tbody></table>';
}

// =====================
// REST API
// =====================

add_action('rest_api_init', function () {
    register_rest_route(STB_REST_NAMESPACE, '/ping', [
        'methods'  => 'GET',
        'callback' => 'stb_rest_ping',
        'permission_callback' => 'stb_check_key',
    ]);

    // Single route, two methods. Calling register_rest_route twice with
    // the same path made WP's REST router behavior depend on call order
    // — the second call would shadow the first, breaking GET. Passing
    // an array of method configs is the documented WP way.
    register_rest_route(STB_REST_NAMESPACE, '/post/(?P<id>\d+)/seo', [
        [
            'methods'  => 'GET',
            'callback' => 'stb_rest_get_post_seo',
            'permission_callback' => 'stb_check_key',
            'args' => ['id' => ['validate_callback' => 'is_numeric']],
        ],
        [
            'methods'  => 'POST',
            'callback' => 'stb_rest_update_post_seo',
            'permission_callback' => 'stb_check_key',
            'args' => ['id' => ['validate_callback' => 'is_numeric']],
        ],
    ]);

    register_rest_route(STB_REST_NAMESPACE, '/attachment/(?P<id>\d+)/alt', [
        'methods'  => 'POST',
        'callback' => 'stb_rest_update_alt',
        'permission_callback' => 'stb_check_key',
        'args' => ['id' => ['validate_callback' => 'is_numeric']],
    ]);

    register_rest_route(STB_REST_NAMESPACE, '/post/(?P<id>\d+)/schema', [
        'methods'  => 'POST',
        'callback' => 'stb_rest_set_schema',
        'permission_callback' => 'stb_check_key',
        'args' => ['id' => ['validate_callback' => 'is_numeric']],
    ]);

    register_rest_route(STB_REST_NAMESPACE, '/posts/list', [
        'methods'  => 'GET',
        'callback' => 'stb_rest_list_posts',
        'permission_callback' => 'stb_check_key',
    ]);

    // Resolve a public URL to a post ID. Used by the SEO Tool's
    // one-click fix flow so users only need a URL, not the post ID.
    register_rest_route(STB_REST_NAMESPACE, '/find', [
        'methods'  => 'GET',
        'callback' => 'stb_rest_find_by_url',
        'permission_callback' => 'stb_check_key',
        'args' => ['url' => ['validate_callback' => fn($v) => is_string($v) && strlen($v) > 3]],
    ]);

    register_rest_route(STB_REST_NAMESPACE, '/revisions', [
        'methods'  => 'GET',
        'callback' => 'stb_rest_revisions',
        'permission_callback' => 'stb_check_key',
    ]);

    register_rest_route(STB_REST_NAMESPACE, '/undo/(?P<rev_id>\d+)', [
        'methods'  => 'POST',
        'callback' => 'stb_rest_undo',
        'permission_callback' => 'stb_check_key',
        'args' => ['rev_id' => ['validate_callback' => 'is_numeric']],
    ]);

    // v0.2.0+ — create a post. Used by daily automation when a blog_draft
    // queue item is approved + published. Status defaults to "draft" so
    // the WP editor gets a final pass before going live; schedules with
    // auto_publish=true pass "publish" to skip that.
    register_rest_route(STB_REST_NAMESPACE, '/posts', [
        'methods'  => 'POST',
        'callback' => 'stb_rest_create_post',
        'permission_callback' => 'stb_check_key',
    ]);
});

function stb_check_key(WP_REST_Request $req): bool
{
    $auth = $req->get_header('authorization') ?? '';
    $expected = get_option(STB_OPTION_KEY);
    if (!$expected) {
        return false;
    }
    $provided = preg_replace('/^Bearer\s+/i', '', $auth);
    return hash_equals($expected, trim($provided));
}

function stb_rest_ping(): WP_REST_Response
{
    return new WP_REST_Response([
        'ok' => true,
        'plugin_version' => STB_VERSION,
        'wp_version' => get_bloginfo('version'),
        'site_url' => home_url(),
        'capabilities' => [
            'meta_titles' => true,
            'meta_descriptions' => true,
            'image_alt' => true,
            'schema' => true,
            'redirects' => true,
        ],
    ]);
}

function stb_get_meta_description(int $post_id): string
{
    // Try the SEO plugins in priority order
    $candidates = [
        '_yoast_wpseo_metadesc',          // Yoast
        'rank_math_description',           // Rank Math
        '_aioseop_description',            // All in One SEO (legacy)
        '_aioseo_description',             // All in One SEO (current)
    ];
    foreach ($candidates as $key) {
        $val = get_post_meta($post_id, $key, true);
        if (!empty($val)) {
            return (string)$val;
        }
    }
    return '';
}

function stb_set_meta_description(int $post_id, string $value): void
{
    // Write to all known plugins so it sticks regardless of which one is active
    update_post_meta($post_id, '_yoast_wpseo_metadesc', $value);
    update_post_meta($post_id, 'rank_math_description', $value);
    update_post_meta($post_id, '_aioseo_description', $value);
}

function stb_record_revision(string $field, string $object, $old, $new): int
{
    $revs = get_option(STB_OPTION_REVISIONS, []);
    $rev_id = count($revs) + 1;
    $revs[] = [
        'rev_id' => $rev_id,
        'ts' => time(),
        'field' => $field,
        'object' => $object,
        'old' => $old,
        'new' => $new,
    ];
    // Cap at last 500 to keep options table small
    if (count($revs) > 500) {
        $revs = array_slice($revs, -500);
    }
    update_option(STB_OPTION_REVISIONS, $revs);
    return $rev_id;
}

function stb_rest_get_post_seo(WP_REST_Request $req): WP_REST_Response
{
    $id = (int)$req['id'];
    $post = get_post($id);
    if (!$post) {
        return new WP_REST_Response(['ok' => false, 'error' => 'Post not found'], 404);
    }
    return new WP_REST_Response([
        'ok' => true,
        'id' => $id,
        'title' => $post->post_title,
        'meta_description' => stb_get_meta_description($id),
        'permalink' => get_permalink($id),
        'status' => $post->post_status,
        'modified' => $post->post_modified,
    ]);
}

function stb_rest_update_post_seo(WP_REST_Request $req): WP_REST_Response
{
    $id = (int)$req['id'];
    $post = get_post($id);
    if (!$post) {
        return new WP_REST_Response(['ok' => false, 'error' => 'Post not found'], 404);
    }
    $body = $req->get_json_params() ?: [];
    $changes = [];

    if (isset($body['title'])) {
        $new = sanitize_text_field($body['title']);
        $old = $post->post_title;
        if ($new !== $old) {
            wp_update_post(['ID' => $id, 'post_title' => $new]);
            $rev_id = stb_record_revision('title', "post:$id", $old, $new);
            $changes[] = ['field' => 'title', 'rev_id' => $rev_id];
        }
    }

    if (isset($body['meta_description'])) {
        $new = sanitize_text_field($body['meta_description']);
        $old = stb_get_meta_description($id);
        if ($new !== $old) {
            stb_set_meta_description($id, $new);
            $rev_id = stb_record_revision('meta_description', "post:$id", $old, $new);
            $changes[] = ['field' => 'meta_description', 'rev_id' => $rev_id];
        }
    }

    return new WP_REST_Response(['ok' => true, 'changes' => $changes]);
}

function stb_rest_update_alt(WP_REST_Request $req): WP_REST_Response
{
    $id = (int)$req['id'];
    $post = get_post($id);
    if (!$post || $post->post_type !== 'attachment') {
        return new WP_REST_Response(['ok' => false, 'error' => 'Attachment not found'], 404);
    }
    $body = $req->get_json_params() ?: [];
    $new = isset($body['alt']) ? sanitize_text_field($body['alt']) : '';
    $old = (string)get_post_meta($id, '_wp_attachment_image_alt', true);
    if ($new !== $old) {
        update_post_meta($id, '_wp_attachment_image_alt', $new);
        $rev_id = stb_record_revision('alt', "attachment:$id", $old, $new);
        return new WP_REST_Response(['ok' => true, 'rev_id' => $rev_id]);
    }
    return new WP_REST_Response(['ok' => true, 'rev_id' => null, 'note' => 'no change']);
}

function stb_rest_set_schema(WP_REST_Request $req): WP_REST_Response
{
    $id = (int)$req['id'];
    $body = $req->get_json_params() ?: [];
    $jsonld = isset($body['jsonld']) ? wp_kses_post($body['jsonld']) : '';
    if (!$jsonld) {
        return new WP_REST_Response(['ok' => false, 'error' => 'jsonld required'], 400);
    }
    $old = (string)get_post_meta($id, '_stb_schema_jsonld', true);
    update_post_meta($id, '_stb_schema_jsonld', $jsonld);
    $rev_id = stb_record_revision('schema', "post:$id", $old, $jsonld);
    return new WP_REST_Response(['ok' => true, 'rev_id' => $rev_id]);
}

// Hook our schema into <head> on relevant pages
add_action('wp_head', function () {
    if (is_singular()) {
        $jsonld = get_post_meta(get_the_ID(), '_stb_schema_jsonld', true);
        if (!empty($jsonld)) {
            echo "\n<!-- SEO Tool: schema -->\n<script type=\"application/ld+json\">$jsonld</script>\n";
        }
    }
});

function stb_rest_list_posts(WP_REST_Request $req): WP_REST_Response
{
    $type = sanitize_key($req->get_param('type') ?? 'post');
    $limit = (int)($req->get_param('limit') ?? 50);
    $limit = max(1, min(200, $limit));

    $posts = get_posts([
        'post_type' => $type,
        'post_status' => 'publish',
        'numberposts' => $limit,
        'orderby' => 'modified',
        'order' => 'DESC',
    ]);

    return new WP_REST_Response([
        'ok' => true,
        'count' => count($posts),
        'posts' => array_map(function ($p) {
            return [
                'id' => $p->ID,
                'title' => $p->post_title,
                'permalink' => get_permalink($p->ID),
                'modified' => $p->post_modified,
                'meta_description' => stb_get_meta_description($p->ID),
            ];
        }, $posts),
    ]);
}

function stb_rest_revisions(): WP_REST_Response
{
    $revs = get_option(STB_OPTION_REVISIONS, []);
    return new WP_REST_Response([
        'ok' => true,
        'revisions' => array_slice(array_reverse($revs), 0, 100),
    ]);
}

function stb_rest_undo(WP_REST_Request $req): WP_REST_Response
{
    $rev_id = (int)$req['rev_id'];
    $revs = get_option(STB_OPTION_REVISIONS, []);
    $found = null;
    foreach ($revs as $r) {
        if (($r['rev_id'] ?? 0) === $rev_id) {
            $found = $r;
            break;
        }
    }
    if (!$found) {
        return new WP_REST_Response(['ok' => false, 'error' => 'Revision not found'], 404);
    }

    [, $object_id_str] = explode(':', $found['object']);
    $object_id = (int)$object_id_str;
    $field = $found['field'];
    $previous = $found['old'];

    switch ($field) {
        case 'title':
            wp_update_post(['ID' => $object_id, 'post_title' => (string)$previous]);
            break;
        case 'meta_description':
            stb_set_meta_description($object_id, (string)$previous);
            break;
        case 'alt':
            update_post_meta($object_id, '_wp_attachment_image_alt', (string)$previous);
            break;
        case 'schema':
            update_post_meta($object_id, '_stb_schema_jsonld', (string)$previous);
            break;
        default:
            return new WP_REST_Response(['ok' => false, 'error' => 'Unsupported field'], 400);
    }

    stb_record_revision($field, $found['object'], $found['new'], $previous);
    return new WP_REST_Response(['ok' => true, 'undone_rev_id' => $rev_id]);
}

/**
 * Resolve a public URL on this WP site to its post / page / CPT id.
 * Falls back through url_to_postid (core), the WP shortlink query, then
 * a manual home-relative path lookup. Returns 404 if nothing matches.
 */
function stb_rest_find_by_url(WP_REST_Request $req): WP_REST_Response
{
    $url = (string)$req->get_param('url');
    if (!$url) {
        return new WP_REST_Response(['error' => 'url required'], 400);
    }

    // Core resolver — handles permalinks, dates, taxonomies.
    $id = url_to_postid($url);
    if ($id > 0) {
        return new WP_REST_Response(['id' => $id]);
    }

    // Try the path relative to home_url (handles language-tagged etc.)
    $home = home_url('/');
    if (str_starts_with($url, $home)) {
        $path = substr($url, strlen($home));
        $maybe = url_to_postid(home_url('/' . ltrim($path, '/')));
        if ($maybe > 0) {
            return new WP_REST_Response(['id' => $maybe]);
        }
    }

    // Last resort: try matching by post_name (slug) of the trailing segment.
    $parts = parse_url($url);
    if (!empty($parts['path'])) {
        $segments = array_filter(explode('/', trim($parts['path'], '/')));
        $slug = end($segments);
        if ($slug) {
            $page = get_page_by_path($slug, OBJECT, ['post', 'page']);
            if ($page) {
                return new WP_REST_Response(['id' => $page->ID]);
            }
        }
    }

    return new WP_REST_Response(['error' => 'not found'], 404);
}

/**
 * Create a new WordPress post. Used by the SEO Tool's daily automation
 * when a blog_draft is approved + published.
 *
 * Body (JSON):
 *   - title           (string, required)
 *   - content         (string, required) — raw HTML
 *   - excerpt         (string, optional)
 *   - status          ("draft" | "publish", default "draft")
 *   - schemaJsonLd    (object | array | null) — saved as _stb_schema_jsonld
 *   - metaDescription (string, optional) — saved via stb_set_meta_description
 */
function stb_rest_create_post(WP_REST_Request $req): WP_REST_Response
{
    $body = $req->get_json_params();
    $title = isset($body['title']) ? sanitize_text_field((string)$body['title']) : '';
    $content = isset($body['content']) ? (string)$body['content'] : '';
    $excerpt = isset($body['excerpt']) ? sanitize_textarea_field((string)$body['excerpt']) : '';
    $status = isset($body['status']) && in_array($body['status'], ['draft', 'publish'], true)
        ? $body['status']
        : 'draft';

    if ($title === '' || $content === '') {
        return new WP_REST_Response(
            ['ok' => false, 'error' => 'title and content are required'],
            400,
        );
    }

    $post_id = wp_insert_post([
        'post_title'   => $title,
        'post_content' => wp_kses_post($content),
        'post_excerpt' => $excerpt,
        'post_status'  => $status,
        'post_type'    => 'post',
    ], true);

    if (is_wp_error($post_id)) {
        return new WP_REST_Response(
            ['ok' => false, 'error' => $post_id->get_error_message()],
            500,
        );
    }

    if (!empty($body['metaDescription'])) {
        stb_set_meta_description($post_id, (string)$body['metaDescription']);
    }
    if (!empty($body['schemaJsonLd'])) {
        update_post_meta(
            $post_id,
            '_stb_schema_jsonld',
            wp_json_encode($body['schemaJsonLd']),
        );
    }

    return new WP_REST_Response([
        'ok'  => true,
        'id'  => $post_id,
        'url' => get_permalink($post_id),
    ]);
}
